# Generated by Django 4.0.6 on 2022-07-26 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=11, max_length=50),
            preserve_default=False,
        ),
    ]
